404: https://act.baival.fun/
github: https://github.baival.fun/
img: https://img.baival.fun/
music: https://music.baival.fun/
proxy: https://proxy.baival.rr.nu/baival/
ps: https://ps.baival.fun/
obj: https://obj.baival.fun/
tool: https://tool.baival.fun/
tetris: https://tetris.baival.fun/
note: https://note.baival.fun/val
